version: '3.4'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waffles_dev
    volumes:
      - .docker-data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432