# Generated by Django 3.0.6 on 2020-05-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200508_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='alias',
            new_name='slug',
        ),
    ]
