# Generated by Django 3.0.6 on 2020-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200508_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='data',
        ),
        migrations.AddField(
            model_name='click',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='click',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
